---
swagger: "2.0"
info:
  description: This is the API documentaion for the COP4331 Contact Manager Small Project
  version: 1.0.0
  title: Contact Manager
  contact:
    email: sh700128@ucf.edu
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: cop4331summer-test.online
basePath: /LAMPAPI
schemes:
- http
paths:
  /Login.php:
    post:
      tags:
      - Users
      summary: Logs in to contact manager app
      description: Logs in to contact manager app
      operationId: doLogin
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: loginItem
        description: Login
        required: false
        schema:
          $ref: '#/definitions/Login'
      responses:
        "200":
          description: OK
        "404":
          description: URL Not Found
  /SignUp.php:
    post:
      tags:
      - Users
      summary: Adds the specified user to to the Users table
      description: Adds the specified user to to the Users table
      operationId: doSignUp
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: signUpItem
        description: SignUp
        required: false
        schema:
          $ref: '#/definitions/SignUp'
      responses:
        "200":
          description: OK
        "404":
          description: URL Not Found
  /ValidateSignUp.php:
    post:
      tags:
      - Users
      summary: Checks if Login is already taken
      description: Checks if Login is already taken
      operationId: doValidateSignUp
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: validationItem
        description: Validate
        required: false
        schema:
          $ref: '#/definitions/ValidateSignUp'
      responses:
        "200":
          description: OK
        "404":
          description: URL Not Found
  /SearchContacts.php:
    post:
      tags:
      - Search
      summary: Searches user's contact table for desired contact(s). Searches all columns in contact table
      description: Searches user's contact table for desired contact(s)
      operationId: doSearchContact
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: searchItem
        description: Search
        required: false
        schema:
          $ref: '#/definitions/Search'
      responses:
        "200":
          description: OK
        "404":
          description: URL Not Found
  /AddContact.php:
    post:
      tags:
      - Add
      summary: Adds the specified contact to the user's contact manager
      description: Adds the specified contact to the user's contact manager
      operationId: doAddContact
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: additem
        description: Add
        required: false
        schema:
          $ref: '#/definitions/Contact'
      responses:
        "200":
          description: OK
        "404":
          description: URL Not Found
  /DeleteContact.php:
    post:
      tags:
      - Delete
      summary: Deletess the specified contact from the user's contact manager
      description: Adds the specified contact from the user's contact manager
      operationId: doDeleteContact
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: deleteitem
        description: Delete
        required: false
        schema:
          $ref: '#/definitions/Delete'
      responses:
        "200":
          description: OK
        "404":
          description: URL Not Found
  /EditContact.php:
    post:
      tags:
      - Edit
      summary: Changes the Values of the given contact to the specified values
      description: Changes the Values of the given contact to the specified values
      operationId: doEditContact
      consumes:
      - application/jason
      produces:
      - application/json
      parameters:
      - in: body
        name: editItem
        description: Edit
        required: false
        schema:
          $ref: '#/definitions/Edit'
      responses:
        "200":
          description: OK
        "404":
          description: URL Not Found
definitions:
  Login:
    type: object
    properties:
      login:
        type: string
        example: JohhnyS
      password:
        type: string
        example: Password1!
  SignUp:
    type: object
    required:
    - FirstName
    - LastName
    - Login
    - Password
    properties:
      FirstName:
        type: string
        example: John
      LastName:
        type: string
        example: Smith
      Login:
        type: string
        example: JohnnyS
      Password:
        type: string
        example: Password1!
  ValidateSignUp:
    type: object
    required:
    - Login
    properties:
      Login:
        type: string
        example: JohhnyS
  Contact:
    type: object
    required:
    - Email
    - FirstName
    - LastName
    - Phone
    - UserID
    properties:
      FirstName:
        type: string
        example: Bob
      LastName:
        type: string
        example: Smith
      Phone:
        type: string
        example: (555)555-5555
      Email:
        type: string
        example: BobSmith@hotmail.com
      UserID:
        type: integer
        example: 4
  Search:
    type: object
    required:
    - Search
    - UserID
    properties:
      Search:
        type: string
        example: J
      UserID:
        type: integer
        example: 4
  Edit:
    type: object
    required:
    - EmailNew
    - FirstNameNew
    - ID
    - LastNameNew
    - PhoneNew
    - UserID
    properties:
      FirstNameNew:
        type: string
        example: Bob
      LastNameNew:
        type: string
        example: Jonson
      PhoneNew:
        type: string
        example: (555)123-4567
      EmailNew:
        type: string
        example: bobj2@outlook.com
      UserID:
        type: integer
        example: 4
      ID:
        type: integer
        example: 23
  Delete:
    type: object
    required:
    - ID
    - UserID
    properties:
      ID:
        type: integer
        example: 23
      UserID:
        type: integer
        example: 4
